{'name': 'VAGIREST Jalali Calendar',
 'version': '17.0.1.5.0',
 'summary': 'Display Jalali dates alongside standard Odoo dates',
 'category': 'VAGIREST Operations',
 'author': 'VAGIREST',
 'license': 'LGPL-3',
 'depends': ['vagirest_production_record', 'sale', 'vagirest_inventory_qms'],
 'data': ['security/security.xml',
          'views/production_qc_views.xml',
          'views/inventory_views.xml',
          'views/production_input_views.xml',
          'views/sale_order_views.xml',
          'views/inventory_qms_jalali_views.xml'],
 'installable': True,
 'application': False,
 'auto_install': False}
