{'name': 'VAGIREST CRM',
 'summary': 'Medical device CRM, sales visits, missions and customer management for VAGIREST',
 'version': '17.0.1.2.0',
 'category': 'Sales/CRM',
 'author': 'Daneshpad Alavi',
 'license': 'LGPL-3',
 'depends': ['crm', 'sale_management', 'contacts', 'stock', 'mail', 'utm'],
 'data': ['security/ir.model.access.csv',
          'data/product_interest_data.xml',
          'views/res_partner_views.xml',
          'views/crm_lead_views.xml'],
 'installable': True,
 'application': False,
 'auto_install': False}
