{'name': 'VAGIREST Inventory QMS',
 'version': '17.0.3.4.0',
 'summary': 'Controlled warehouse and QMS documents for VAGIREST',
 'author': 'VAGIREST',
 'category': 'Inventory',
 'license': 'LGPL-3',
 'depends': ['base', 'stock', 'mail', 'vagirest_production_record'],
 'data': ['security/security.xml',
          'security/ir.model.access.csv',
          'data/sequence.xml',
          'views/product_template_views.xml',
          'views/raw_material_receipt_views.xml',
          'data/f01_f04_sequence.xml',
          'views/material_request_views.xml'],
 'application': True,
 'installable': True}
